services:
  postgres:
    image: postgres:15-alpine
    container_name: bsbd_lab1_db
    environment:
      POSTGRES_DB: bsbd_lab1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5433:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./test_security_complete.sql:/test_security_fixed.sql
      - ./test_login_logging_complete.sql:/test_login_logging_complete.sql
      - ./test_lab2_security.sql:/test_lab2_security.sql
      - ./lab2_rule_benchmark.sql:/lab2_rule_benchmark.sql
      - ./test_sensitive_functions.sql:/test_sensitive_functions.sql
      - ./test_lab3_rls.sql:/test_lab3_rls.sql
      - ./migrate_lab4.sql:/migrate_lab4.sql
      - ./test_lab4.sql:/test_lab4.sql
      - ./lab4_performance_analysis.sql:/lab4_performance_analysis.sql
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  pgadmin:
    image: dpage/pgadmin4
    container_name: bsbd_lab1_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: 123
    ports:
      - "8080:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
