listen_addresses = '*'
password_encryption = 'scram-sha-256'

ssl = on
ssl_cert_file = '/etc/postgresql/ssl/server.crt'
ssl_key_file  = '/etc/postgresql/ssl/server.key'

hba_file = '/etc/postgresql/lab3_sem6_pg_hba.conf'

