listen_addresses = '*'
port = 5432
max_connections = 100

wal_level = replica
archive_mode = on
archive_command = '/usr/local/bin/lab4_sem6_archive_wal.sh %p %f'
archive_timeout = 60
max_wal_senders = 10
wal_log_hints = on

restore_command = '/usr/local/bin/lab4_sem6_restore_wal.sh %f %p'

logging_collector = on
log_directory = 'log'
log_filename = 'postgresql-%Y-%m-%d.log'
